package com.tignioj.config;

public class MyConfig {
   //SHP文件Start=======================================================
   public static final String PERSONAL_SHP_CONFIG_DB = "personal_shp_config_db";

   //app setting
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_ENABLE_WEATHER= "PERSONAL_SHP_CONFIG_KEY_ENABLE_WEATHER";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_CITY_CODE = "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_CITY_CODE";
   public static final String PERSONAL_SHP_CONFIG_KEY__APP_SETTING_SHOW_SECOND = "PERSONAL_SHP_CONFIG_KEY_SHOW_SECOND";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_CITY_NAME = "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_CITY_NAME";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_IS_NIGHT_MODE = "PERSONAL_SHP_CONFIG_KEY_IS_NIGHT_MODE";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_SCREEN_ALWAYS_ON = "PERSONAL_SHP_CONFIG_KEY_ALWAYS_ON";

   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_CLOCK= "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_CLOCK";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_COUNTDOWN= "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_COUNTDOWN";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_EVENT= "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_EVENT";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_NOTE= "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_NOTE";

   //date
   public static final String PERSONAL_SHP_CONFIG_KEY_COUNTDOWN_TARGET_DATE = "PERSONAL_SHP_CONFIG_KEY_TARGET_DATE";
   public static final String PERSONAL_SHP_CONFIG_KEY_COUNTDOWN_EVENT_TEXT = "PERSONAL_SHP_CONFIG_KEY_EVENT_TEXT";
   public static final String PERSONAL_SHP_CONFIG_KEY_COUNTDOWN_NOTES = "PERSONAL_SHP_CONFIG_KEY_NOTES";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_HE_WEATHER_APIKEY = "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_HE_WEATHER_APIKEY";
    public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_DATE = "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_DATE";
   public static final String PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_WEATHER = "PERSONAL_SHP_CONFIG_KEY_APP_SETTING_TEXTSIZE_WEATHER";

   //Shp文件End=============================================================
}
